### ISSUE TITLE
www.google.com/jsapi reference uses http instead of https

### ISSUE THREAD

**Issue by fredvd** [eea/eea.app.visualization#4]
eea.app.visualisation contains a hard reference to http://www.google.com/jsapi which gives mixed mode issues when servin daviz over https systems. 
Can this be changes to // to use http/https or better, use https always as is already done in eea.googlecharts?

https://github.com/eea/eea.app.visualization/blob/master/eea/app/visualization/browser/zpt/edit.pt#L11

**Comment by zotya** [comment]
Hi,

It is fixed, and it will be included in the next egg release, in maximum 2 weeks

**Comment by alecghica** [comment]
Fixed in 466903fb48cfef6401efa01dc3f75bd22fb7bbca.

**Comment by MistyAnn** [comment]
Show&Tell;not kiss and tell!See and Say(nomore)!!!Monkey see;Monkey do...ALL FOR ME&YOU?Like Goldylock's,in baby bears bed("and she's still there")
